---
- name: Remove the down docker
  copy:
    src: clean.sh
    dest: /home/docky/clean.sh
    mode: 0777

- name: Execute the script
  shell: |
       if [ ! -f removeNode.txt ] ; then 
          touch removeNode
       fi
       ./clean.sh removeNode
  ignore_errors: yes

