---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a

- include_tasks: hostname.yml

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: True

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - openssh-server  
#    - docker.io
    - docker-ce=17.06.2~ce-0~ubuntu #Kubernetes aime pas les version récentes
    - apt-transport-https
    - curl

- name: Prepare the install of kubernetes
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    warn: False

- name: create /etc/apt/sources.list.d/kubernetes.list
  file:
    path: '/etc/apt/sources.list.d/kubernetes.list'
    state: touch

- name:
  lineinfile: dest=/etc/apt/sources.list.d/kubernetes.list
              regexp='^'
              line='deb http://apt.kubernetes.io/ kubernetes-xenial main'
              state=present

- name: Install kubernetes packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - kubelet  
    - kubeadm
    - kubectl

- name: configure environnement
  lineinfile: dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
              insertbefore='^ExecStart='
              line='Environment=”cgroup-driver=systemd/cgroup-driver=cgroupfs”'
              state=present

- include_tasks: '{{ kubernetes_node_type }}.yml'

