---
#Appel au script de faas-cli
#- include_tasks: faas-cli.yml
#Initialisation de docker en tant que manager si il est inactivé
- name: Init docker swarm
  shell: |
    if [ "$(docker info | grep Swarm | sed 's/Swarm: //g')" == "inactive" ]; then
        docker swarm init;
    fi
  args:
    executable: /bin/bash
#Appel au script d'installation d'openfaas
#- include_tasks: openfaas.yml
